baseURL = 'https://guidosalustri.github.io/papelonstudio/'
languageCode = 'en-us'
title = 'Papelon Studio'
theme = 're-terminal'

[params]
  themeColor = 'paper'
  contentTypeName = 'posts'

[languages]
  [languages.en]
    title = 'Papelon Studio'
    [languages.en.params]
      subtitle = 'A Retro Tabletop Space'
      keywords = ''
      copyright = ''
      readMore = 'Read more'
      readOtherPosts = 'Read other posts'
